

####  Unusual Volume Scans.ts
# https://tosindicators.com/scans/unusual-volume
# Unusual Volume Scanner for ThinkOrSwim

# Generated by TOS Indicators

# Full tutorial: tosindicators.com/indicators/unusual-volume

# Scan 1: 4+ Standard Deviation Volume Bursts

plot signal = RelativeVolumeStDev(50).RelVol >= 4;

# Scan 2: Multi-Day Volume Consistency

def volumeCondition = RelativeVolumeStDev(50).RelVol >= 3;

plot multiDaySignal = Sum(volumeCondition, 5) >= 3;

# Scan 3: Volume + Moving Average Confluence

def sma50 = SimpleMovingAvg(close, 50);

def sma200 = SimpleMovingAvg(close, 200);

def smaCondition = close crosses above sma50 and close > sma200;

def volumeCond = RelativeVolumeStDev(50).RelVol >= 3;

plot maVolumeSignal = smaCondition and volumeCond;

# Scan 4: Options Unusual Volume (for Options Hacker)

# Use in conjunction with:

# – Open Interest > 3000

# – Volume > 300

# – Delta between 0.4-0.6

plot optionsSignal = RelativeVolumeStDev(50).RelVol >= 3;

