[project]
name = "schwab-trader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=26.3.0",
    "dash>=4.0.0",
    "dash-bootstrap-components>=2.0.4",
    "dash-table>=5.0.0",
    "dask>=2026.1.2",
    "dotenv>=0.9.9",
    "filelock>=3.25.0",
    "ipykernel>=7.2.0",
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "plotly>=6.6.0",
    "pydantic>=2.12.5",
    "pytz>=2026.1.post1",
    "requests>=2.32.5",
    "rich>=14.3.3",
    "schwabdev",
    "seaborn>=0.13.2",
]

[tool.uv.sources]
schwabdev = { path = "../github-lib/schwabdev", editable = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/schwab_trader"]


# Python uses the build backend (Hatchling) to create a wheel. (Python installs packages from wheels. This project is also treated as a package).
# What a “Wheel” Is: A wheel contains: 1. compiled binaries (if needed) 2. package files 3. metadata. Installing from a wheel is basically unzipping files, which is very fast.
# How uv Is Different: uv maintains a shared global cache for all Python environments on your machine (~/.cache/uv).

# editable install behavior: uv installs packages specified dependencies mormally as wheels into site-packages. Those are not editable. When you run `uv sync` you will see `schwab-trader==0.1.0 (from file:///home/zhaohuiwang/dev/finance-project/schwab-trader)` You local project is in the path specified in the parentheses is referred as `schwab-trader==0.1.0`. Any edits you make in your local project are immediately visible in python without reinstalling. Now you can `from schwab_trader.utils.db import init_db; import sachwab_trader`. So editable install behavior is basically a link (via a .pth file) from the virtual environment to your local project.