

# ====================== Trading Bot Configuration ======================
# schwab-trader/conf/momentum_config.yaml


symbol: "APLD"
account_number: "29308909"

# Strategy Parameters
stop_price_link_type: "PERCENT"


down_window_min: 20
buy_quantity: 1500

up_window_min: 15

# ATR-based Strategy
atr_period: 14
up_atr_multiplier: 1.5
trailing_atr_multiplier_sell: 2.0

down_atr_multiplier: 1.25
trailing_atr_multiplier_buy: 1.5
buy_fallback_offset_pct: 0.5   # below current price for fallback limit buy


# Risk Management
daily_max_loss_pct: 3.0
max_position_shares: 1500

# Trading Hours
trade_only_regular_hours: true
trade_pre_market: false
trade_after_hours: false

market_open_time: "09:45"   # YOU MAY WANT TO IGNORE THE FIRST 15 MINS
market_close_time: "16:00"

# Operation
check_interval_sec: 5

# Logging
log_file: "logs/nbis_trades.csv"

# Telegram
telegram:
  enabled: false
  token: ""
  chat_id: ""
