
# schwab-trader/conf/bot3_conf.yaml

# To change the dashboard port(from 8050 to 8051)
# How you run             Where to change
# Manual terminal         --port 8051 on the command linesy
# stemd service           ExecStart=... --port 8051
# New permanent default   default=8051 in bot3.py

# Stop loss orders with loss dollar/pct parameters is based on (in the order) 1. the day high (memory or SQLite DB). 2. actual buy price from Schwab. 3. buy_target_price. stop_loss_dollar preceeds stop_loss_pct. Options: proper configuration (buy_target_price < calcualte stop loss price), to sell when market plunge and buy back at lower price point.

# Stop loss order is set as duration: "GOOD_TILL_CANCEL", all other orders are duration: "DAY"

symbols:
    WDC:
      fixed_shares: 100
      
      buy_target_price: 464 #468.1

      trail_activation_price: 466 #478  # threshold to trigger trailing sell order
      trail_offset_pct: 0.2       # minimal 0.1, trail sell by % from high
      limit_sell_price: 595.5     # hard take-profit limit
      co: 0                       # order cycle options


      session: "NORMAL"
      duration: "DAY"

      stop_loss_dollar: 0
      stop_loss_pct: 10.0            # ignored while dollar > 0
      stop_loss_order_duration: "GOOD_TILL_CANCEL"
      
      buy_drop_pct: 5.0              

    
    MU:
      fixed_shares: 50
      
      buy_target_price: 965.2

      trail_activation_price: 1025   # threshold to trigger trailing sell order
      trail_offset_pct: 0.2           # trail sell by % from high
      limit_sell_price: 1200         # hard take-profit limit
      co: 0

      session: "NORMAL"
      duration: "DAY"

      stop_loss_dollar: 0
      stop_loss_pct: 10.0            # ignored while dollar > 0
      stop_loss_order_duration: "GOOD_TILL_CANCEL"
      
      buy_drop_pct: 5.0 



risk:
  risk_per_trade_pct: 1.0
  max_positions: 4
  min_account_equity: 5000.0
  max_daily_loss_pct: 3.0
  default_shares: 1

# Auto-shutdown configuration
# auto_shutdown_after_close: False
# shutdown_buffer_minutes: 2
# shutdown_on_weekends: true
