
# schwab-trader/conf/bot3_conf.yaml

# To change the dashboard port(from 8050 to 8051)
# How you run             Where to change
# Manual terminal         --port 8051 on the command linesy
# stemd service           ExecStart=... --port 8051
# New permanent default   default=8051 in bot3.py

symbols:
    WDC:
      fixed_shares: 200
      
      buy_target_price: 401.1

      trail_activation_price: 460.5   # threshold to trigger trailing sell order
      trail_offset_pct: 0.1           # trail sell by % from high
      limit_sell_price: 485.5         # hard take-profit limit

      stop_loss_dollar: 0
      stop_loss_pct: 8.0            # ignored while dollar > 0
      
      buy_drop_pct: 5.0              

    
    MU:
      fixed_shares: 49
      
      buy_target_price: 830.1

      trail_activation_price: 940   # threshold to trigger trailing sell order
      trail_offset_pct: 1           # trail sell by % from high
      limit_sell_price: 990         # hard take-profit limit

      stop_loss_dollar: 0
      stop_loss_pct: 8.0            # ignored while dollar > 0
      
      buy_drop_pct: 5.0 



risk:
  risk_per_trade_pct: 1.0
  max_positions: 4
  min_account_equity: 5000.0
  max_daily_loss_pct: 3.0
  default_shares: 1

# Auto-shutdown configuration
# auto_shutdown_after_close: False
# shutdown_buffer_minutes: 2
# shutdown_on_weekends: true
