
# schwab-trader/conf/simple_bot_conf.yaml

symbols:
  # ACHR:
  #   buy_target_price: 6.20
  #   limit_sell_price: 6.30  # primary fixed price (used most of the time)
  #   buy_drop_pct: 20.0
  #   limit_sell_pct: 15.0    # the % used in fallback 
  #   stop_loss_dollar: 0.6
  #   stop_loss_pct: 15.5
  #   fixed_shares: 2900
  # NBIS:
  #   buy_target_price: 225.1
  #   limit_sell_price: 255.1
  #   buy_drop_pct: 20.0
  #   limit_sell_pct: 15.0
  #   stop_loss_dollar: 20
  #   stop_loss_pct: 15.5
  #   fixed_shares: 300
  # JOBY:
  #   buy_target_price: 8.95
  #   limit_sell_price: 9.02
  #   stop_loss_dollar: 2.0
  #   buy_drop_pct: 20.0
  #   limit_sell_pct: 15.0
  #   stop_loss_pct: 15.5
  #   fixed_shares: 3500
  # APLD:
  #   buy_target_price: 28.6
  #   limit_sell_price: 34.8
  #   buy_drop_pct: 20.0
  #   limit_sell_pct: 15.0
  #   stop_loss_dollar: 5
  #   stop_loss_pct: 10
  #   fixed_shares: 1600

# Never touch CRWV !!!!!! This is one of the worst performing stocks.
  # CRWV:
  #   buy_target_price: 81.5
  #   limit_sell_price: 84.8
  #   stop_loss_dollar: 5.0
  #   buy_drop_pct: 10.0
  #   limit_sell_pct: 8.0
  #   stop_loss_pct: 8.0
  #   fixed_shares: 700
  # IBM:
  #   buy_target_price: 248.4
  #   limit_sell_price: 273.4
  #   stop_loss_dollar: 0.5
  #   buy_drop_pct: 10.0
  #   limit_sell_pct: 8.0
  #   stop_loss_pct: 8.0
  #   fixed_shares: 300

  # USAR:    
  #   buy_target_price: 25
  #   limit_sell_price: 30.5
  #   buy_drop_pct: 20.0
  #   limit_sell_pct: 15.0
  #   stop_loss_dollar: 3.0
  #   stop_loss_pct: 15.5
  #   fixed_shares: 38
  WDC:
    buy_target_price: 445.5
    limit_sell_price: 465.5
    stop_loss_dollar: 5.0
    buy_drop_pct: 10.0
    limit_sell_pct: 8.0
    stop_loss_pct: 8.0
    fixed_shares: 200
risk:
  risk_per_trade_pct: 1.0
  max_positions: 4
  min_account_equity: 5000.0
  max_daily_loss_pct: 3.0
  default_shares: 1

# Auto-shutdown configuration
auto_shutdown_after_close: False
shutdown_buffer_minutes: 2
shutdown_on_weekends: true
